name: jltest
favicon: null
layout_spectrum: 0.08062421530485153
typography_spectrum: 0.6389027570839971
title: This is a test site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.402826638892293
  lightness: 0.9621805972419679
  saturation: 0.09834045311436057
  rhythmicContrast: 0.11201220680959523
purpose: []
