name: jltest
favicon: null
layout_spectrum: 0.08062421530485153
typography_spectrum: 0.6389027570839971
title: This is a test site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#67a4e7'
    - '#6f793c'
    - '#18241a'
    - '#bec6bb'
    - '#fffefa'
  brandStrength: 0.875
  lightness: 1
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
